services:
  bidwize-core:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/opt/app
      - ../requirements.txt:/opt/app/requirements.txt
    env_file:
      - ../.env
    networks:
      - bidwize

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bidwize

networks:
  bidwize:
    driver: bridge

volumes:
  db-data:
    driver: local