
services:
  bidwize-core:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/opt/app
      - ../requirements.txt:/opt/app/requirements.txt
    networks:
      - bidwize

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: bidwize_user
      POSTGRES_PASSWORD: bidwize_password
      POSTGRES_DB: bidwize_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bidwize

networks:
  bidwize:
    driver: bridge

volumes:
  db-data:
    driver: local
